### ISSUE TITLE
Lag caused by aura

### ISSUE THREAD

**Issue by farigiss** [Ellpeck/NaturesAura#159]
I'm playing the Heavens of Sorcery modpack v0.10.1.3 with Nature's Aura v18.1. 
But I have also experienced this like a year ago on another pack.

I'm using a setup like this (https://i.imgur.com/ASeUs9P.png) to fire snowballs at a Shooting Mark. This produces a lot of aura.
I left it on overnight and suddenly my server TPS increased by 15-20 TPS, and there are also micro lag spikes now every 1 or 2 seconds. It's easy to see. Redstone contraptions just halt, rabbits hang mid-jump for a split second, etc.

LagGoggles shows this (https://i.imgur.com/TJWSzU6.png). But this is an average over 30 seconds and I think it mainly manifests as lag spikes. So it's actually way worse than 19~ ms/t, when it spikes.

I now have max aura in a huge area, and if I had to guess, I think it's trying to balance itself over the whole area which could be computationally expensive.

Is there anything I can do in the meantime to reset my aura to 0 as if this never happened?

**Comment by Ellpeck** [comment]
Please use the [vanilla profiler](https://minecraft.gamepedia.com/Commands/debug) and send the resulting report. Also, you can use the `naaura` command to modify the aura in the area.

**Comment by farigiss** [comment]
Wow I had no idea there was a built-in profiler. Will this do?

[profile-results-2020-11-22_00.17.43.txt](https://github.com/Ellpeck/NaturesAura/files/5578634/profile-results-2020-11-22_00.17.43.txt)

**Comment by Ellpeck** [comment]
Yea, this is what I expected: All of the effects querying the chunks in the area separately caused the low TPS. Since the 1.12 branch isn't maintained anymore except for extremely important issues (which I don't consider this one to be), I will close this one for now. If you encounter this issue again in the 1.16 version (which has had some changes that likely made this go away), please reopen this issue or create a new one.

Keep in mind that you can use an Aura Detector to automatically cause your setup to be shut off once there is enough aura in a certain area.
