### ISSUE TITLE
[Feature Request] Configurable pollution producing blocklist

### ISSUE THREAD

**Issue by Normal69** [Ellpeck/NaturesAura#17]
Howdy?

The naturesaura.cfg would be nice if a list could be provided what block entities should be used for pollution?
For example, when I let in Techreborn, this would be a nice surprise.
If you find the idea evil enough, a lot of evil admins will praise your name. :+1: 

Most reverently:
Normal

**Comment by Ellpeck** [comment]
I don't see how this would be possible?
How would Nature's Aura know how much Aura the machines should drain and when they should acutally actively drain it (because surely that should only happen while they're in use)?
Nature's Aura has an easy to implement API, and I think this would be a feature much better suited for the individual mods that want to support it themselves, as I don't really see how this would be possible to be implemented on my side in a generic way.
I'm sorry, but thanks for the suggestion!
