### ISSUE TITLE
Natural Altar Recipes

### ISSUE THREAD

**Issue by Keetarin** [Ellpeck/NaturesAura#203]
Three related questions:
Q1: Is there a way to add recipes to the natural altar?
Q2: If the answer is no to Q1, are you still adding/backporting features to the 1.12.x versions
Q3: If yes to Q2, would you be willing to add CraftTweaker integration to it. 
I would love to make recipes for the natural altar. 
Specifically I would like to gate Nature's Compass behind it so that if you want to find biomes easily, you would need to make an Ender Compass and infuse it with Aura to "attune it to nature".
Edit: Just realized you wouldn't need CraftTweaker for this, just a a way to designate input & outputs for the altar. Even so, I still want to know about Q1 & Q2.

**Comment by Ellpeck** [comment]
The 1.12 version [has CraftTweaker compatibility](https://github.com/Ellpeck/NaturesAura/blob/1.12/CraftTweakerCompat.md). Future versions don't need explicit CraftTweaker compatibility, because they use vanilla Minecraft's JSON recipe system, which can be changed by CraftTweaker and mods like KubeJS natively.
