### ISSUE TITLE
Error when launching (1.19.2)

### ISSUE THREAD

**Issue by festro** [Ellpeck/NaturesAura#306]
upon launching the game will load a few bars before foing into the error reporting screen with this mod reported as the cause.
Here's the log.
[crash-2023-04-12_16.12.14-fml.txt](https://github.com/Ellpeck/NaturesAura/files/11216798/crash-2023-04-12_16.12.14-fml.txt)

**Comment by Ellpeck** [comment]
This issue has nothing to do with Nature's Aura. It's an exception caused by a mixin called `imm_ptl.mixins.json:common.chunk_sync.MixinChunkMap_C`, and Nature's Aura just happened to be the first one to load the class that caused the issue.

I assume you have a mod installed that is called something like "Chunk Sync" or something that's similar to "Imm Ptl", which is the one that is causing this issue!

**Comment by festro** [comment]
Judging by the id it's Immersive Portals (for Forge).
