### ISSUE TITLE
[1.18.2] Book Of Natural Aura do not work .

### ISSUE THREAD

**Issue by Hegary-YT** [Ellpeck/NaturesAura#313]
hello problem with the book of natural aura because it detects that things are missing. I give an error image as well as the logs .
![Capture](https://github.com/Ellpeck/NaturesAura/assets/75640299/4b281a3d-a238-42db-8444-9e3232438c60)
[latest.log](https://github.com/Ellpeck/NaturesAura/files/11826120/latest.log)

**Comment by Ellpeck** [comment]
This is caused by a recipe in the book being removed in the modpack, or an item from Nature's Aura being removed from the modpack:
```
Caused by: java.lang.RuntimeException: Error while loading entry naturesaura:using/crushing_catalyst page 7
[...]
Caused by: java.lang.RuntimeException: Unknown item ID: naturesaura:altar
```
For Patchouli books to work correctly in modpacks that change a lot of recipes or items, overrides for the books have to be created using datapacks that take these changes into account.
