### ISSUE TITLE
Admin improvements for aura debugging

### ISSUE THREAD

**Issue by R-Sharafaldin** [Ellpeck/NaturesAura#314]
Currently running an ATM8 server and Nature's Aura is killing my TPS reducing it from 20 to 9.

It's mostly one player that uses Nature's Aura and it seems like the Abundant Aura effects are causing TPS lag.

Spark Profile: https://spark.lucko.me/LbRZai1cuh

Minecraft version: 1.19.2
ATM8 19b
![image](https://github.com/Ellpeck/NaturesAura/assets/45421266/bf2c8334-6447-4f1d-bd87-4b078fb7554d)

**Comment by R-Sharafaldin** [comment]
Seems like this was a previous issue aswell https://github.com/Ellpeck/NaturesAura/issues/246

Is Nature's Aura just not optimised for constant running bases?

**Comment by Ellpeck** [comment]
Hi! Nature's Aura is constantly receiving additional optimization updates. Unfortunately, passively influencing the environment in the way that Nature's Aura does is not something that Minecraft, or Forge, are particularly built to do, which is why the mod has to use a lot of hacks to do so.

As explained in the Book of Natural Aura, players are encouraged to use the Aura Detector to stop their generation once their base has enough Aura in it.

Nature's Aura was initially designed to allow players to do as much as they want with Aura, but unfortunately this doesn't appear feasible on servers - it's a bit like a server admin allowing players to do whatever they want with dropped items, only for a single player to have a mechanism that accidentally drops hundreds of thousands of items into the world on a regular basis. 

I've been considering for a long time adding an option that allows capping either the size of an area that contains Aura, or the amount of Aura that an area can contain, so this issue can more easily be avoided on servers.

**Comment by R-Sharafaldin** [comment]
Awesome! Thanks for the max range. I think this will benefit the mod greatly.

Out of curiosity, where in the book does it encourage stopping generation? The Aura Detector entry simply mentions that it's a nice have to monitor aura from what i can see. 
![image](https://github.com/Ellpeck/NaturesAura/assets/45421266/3e346877-c1e4-4b70-88e5-71ade1904540)

Also, while the new max range fixes future problems, resetting aura in a large area already affected is a pain for two reasons:

1. You can only see debug aura in creative, not spectator, and it spreads underground aswell, making an Xray resource pack almost a neccessity.
2. The /naaura reset mod only has a 35 block radius

Would it be possible to implement any of these changes aswell?
