### ISSUE TITLE
[1.19.2] Ticks fluctuations due to AuraChunk

### ISSUE THREAD

**Issue by jinkhya** [Ellpeck/NaturesAura#322]
Hello, 
I'm hosting an Enigmatica 9 Expert server and ran a spark profiler with `--only-ticks-over 500` for about 5 minutes as I was seeing some delay in interacting with things. Here's the report: 
https://spark.lucko.me/ULb7A6HRwC

Only 2 players were online including myself who isn't very advanced and chunkloading is limited to players being online. 

Thanks in advance,
Jin

**Comment by Ellpeck** [comment]
Hi! Was this world created before Nature's Aura 38.0 was released? That version introduced a system called aura fizzling that also mitigates lag caused by a lot of aura in the area. Unfortunately, this system cannot be applied to old aura spots, meaning that areas that already had a large amount of aura will continue to cause more lag than usual. You can travel to these areas and use the ` /naaura reset <range>` command to reset the aura in that area. Any aura added to it in the future will then fizzle correctly, causing no further lag to be generated.
