### ISSUE TITLE
Invalid Patchouli recipes crash the game (instead of just failing to load on the page)

### ISSUE THREAD

**Issue by mberlin1** [Ellpeck/NaturesAura#339]
to reproduce: take nature's aura guidebook, open it, select the "harnessing aura" category, select the "the natural altar" item and scroll through the instructions. crash will happen after 2 or 3 pages.

[crash-2023-12-01_10.45.10-client.txt](https://github.com/Ellpeck/NaturesAura/files/13529929/crash-2023-12-01_10.45.10-client.txt)

top of stack says its "missing a recipe" i'm unsure what recipe:
java.lang.NullPointerException: Cannot read field "catalyst" because "this.recipe" is null
is part of.  

If this is due to recipes being changed, it would be really helpful if i knew what recipes were on the pages in that section so i could try and track the problem on the modpack. Thank you.

**Comment by Ellpeck** [comment]
Hi! This issue is in fact caused by a recipe change that isn't reflected in the book, but it's not meant to outright crash the game, just fail to display on the page. 

You can find the full content of the book [in this repository](https://github.com/Ellpeck/NaturesAura/tree/main/src/main/resources/assets/naturesaura/patchouli_books/book/en_us), so it should be pretty easy to figure out what page the issue appears on based on the info you provided. Good luck!

**Comment by mberlin1** [comment]
thank you very much.
