### ISSUE TITLE
Abusive behaviour on private server

### ISSUE THREAD

**Issue by toastercat543** [Ellpeck/NaturesAura#348]
this mod purposely crashed my server and refused to allow it to start until i enabled one negative effect it crashed with an illegal state exception which confirms the crash was deliberate you never stated that you added this in any of your changelogs. remove this "feature" please. i am not cheating i am not copying your work i am playing your mod. i like the tools you have created i like the plants trees and additional blocks i hate being punished for progressing through a pack. i'm just trying to have fun with my friends and we cant if every world ends up ruined because we don't want to play this way or the game refuses to load because we changed an option in your config. just please remove this limitation and all is well. best regards toastercat543

**Comment by Ellpeck** [comment]
uuuuh what are you referring to? can you share some logs please?

**Comment by Ellpeck** [comment]
OH I understand now what you're trying to say, sorry!

Yes, disabling every negative imbalance effect is not allowed. This is not a recent change by any means; it's been a thing since [early 2020](https://github.com/Ellpeck/NaturesAura/commit/c0806e3419e8d9db69f778b7f7c47351889d1262). 

This isn't the mod "punishing the player for progressing through a pack", though - you're not *meant* to drain aura so much that you get the negative effects, you're meant to generate aura to offset the amount you use. That's an inherent part of the mod's gameplay, and so I have no intention of changing this limitation. Sorry!

The mod is MIT licensed, though, so feel free to create a fork and/or a private build for your server that has the mentioned code commented out :)

**Comment by toastercat543** [comment]
can you do that for me? because i have no clue how? you should change this limitation because it refused to allow my server i paid 150 dollars for to start.

**Comment by Ellpeck** [comment]
Again, I have no intention of changing this limitation.

**Comment by toastercat543** [comment]
than can you create a fork and/or a private build for your server that has the mentioned code commented out?
