### ISSUE TITLE
CraftTweaker Integration Issue/Patchouli

### ISSUE THREAD

**Issue by ChosenArchitect** [Ellpeck/NaturesAura#43]
When changing a nonritual items recipe the book CT can't read the format required for Patchouli.

```recipes.addShapeless("naturesaura:gold_fiber", <naturesaura:gold_fiber> * 4, [<minecraft:tallgrass:1>,<minecraft:dye:11>]); ```

"naturesaura:gold_fiber" is causing an issue with crafttweaker 

CT throws a warning about naturesaura:gold_fiber containing a ':'

**Comment by Ellpeck** [comment]
_Note to self:
We agreed to work around this by hardcoding CraftTweaker compat into Patchouli so that it looks for recipes with the CT prefix if the normal ones aren't found. 
This should also be added to the CraftTweakerInfo file, and maybe all other recipe types within NA should be changed to automatically be prefixed with crafttweaker: also._
