### ISSUE TITLE
Lag from onChunkWatch Event

### ISSUE THREAD

**Issue by Darkere** [Ellpeck/NaturesAura#84]
Recently exploring the world has gotten a log laggier and actually impacts TPS quite a bit. We used spark to analyze it and it seems the reason it happens is natures aura using getChunk in the onChunkWatch event causing the thread to stall?

![image](https://user-images.githubusercontent.com/4283717/75626350-3e4bdc80-5bc7-11ea-9f69-9c49fac4949f.png)

Spark report: https://sparkprofiler.github.io/#DYPA2p84TY

Forge-31.1.18
NaturesAura-22.0

**Comment by Ellpeck** [comment]
my God, the 1.14+ chunk stuff is so broken bleh

**Comment by Ellpeck** [comment]
Would be great if you could test this version. You should also make sure that clients still properly receive inforamtion about Aura in chunks they load (by just using an Environmental Eye on a client), since I couldn't do that much testing because I'm not near my computer. If everything looks good, you can just close this issue. Thanks! https://ci.ellpeck.de/blue/organizations/jenkins/NaturesAura/detail/master/25/artifacts

**Comment by Darkere** [comment]
Fixed :)
Environmental Eye also shows aura working. (found a place with an almost full aura bar o.O)
