### ISSUE TITLE
Crash Cannot get property IntegerProperty as does not exist in Block{minecraft:void_air}

### ISSUE THREAD

**Issue by Darkere** [Ellpeck/NaturesAura#89]
User is crashing apparently at random times.

Crashlog: https://hatebin.com/rkgvhmndzy

Forge: 31.1.18
NaturesAura-23.2

Original issue: https://github.com/Team-RAM/RAM/issues/28

**Comment by Ellpeck** [comment]
It looks like you're using a mod that injects Mixins into the game (MixinBootstrap-1.0.2.jar). Please remove this mod and any of its dependencies and try to reproduce the error.

**Comment by Darkere** [comment]
Here you go: https://hatebin.com/atrystpckc

**Comment by Ellpeck** [comment]
Can you try to reproduce it with just Nature's Aura? I can't seem to be able to, but it might somehow be a world-specific issue.

**Comment by Darkere** [comment]
Surprisingly enough that is actually possible.
https://hatebin.com/ltorjeenqo

**Comment by Ellpeck** [comment]
Hahaaa, well this is an interesting one. If bamboo is grown by Nature's Aura while it's close to the top of the world, this crash occurs.
HOWEVER, since bone meal uses the exact same grow code (because it calls the same method), bone meal *also* causes an exception to be thrown on the server side when used that high up. Vanilla is buggy, huh.

**Comment by Darkere** [comment]
Ah. Player is right next to an amplified bamboo forest. That poses a problem though. Those aren't that rare.
